# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='tenant_name',
            new_name='created_tenant_id',
        ),
    ]
