# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0004_regionsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionsettings',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userdb.Region'),
        ),
    ]
