# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0005_auto_20160712_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionsettings',
            name='public_network_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionsettings',
            name='requires_network_setup',
            field=models.BooleanField(default=False),
        ),
    ]
