# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0006_auto_20160714_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created_network_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
