# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0011_auto_20160717_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionsettings',
            name='public_network_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
