# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openstack', '0012_regionsettings_public_network_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
