# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='address',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='groupprofile',
            old_name='bio',
            new_name='held_mrc_grants',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='ustid',
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='institution',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='intended_climb_use',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='position',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='research_interests',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
