# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0002_auto_20160629_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='held_mrc_grants',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='intended_climb_use',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='research_interests',
            field=models.TextField(),
        ),
    ]
