# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0002_auto_20160629_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='institution',
            field=models.CharField(max_length=100),
        ),
    ]
