# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0006_auto_20160711_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='to_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdb.Team', verbose_name='Team to invite user to'),
        ),
    ]
