# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0009_auto_20160711_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
