# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0010_team_verified'),
    ]

    operations = [
    ]
