# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 21:32
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0012_auto_20160711_2131'),
    ]

    operations = [
    ]
