# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0016_auto_20160712_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tenants_available',
            field=models.BooleanField(default=False),
        ),
    ]
