# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0018_region_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
